
// This file has been generated by the GUI designer. Do not modify.
namespace DI
{
	public partial class WindowCreateDatabase
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Entry entry1;

		private global::Gtk.Button button4;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DI.WindowCreateDatabase
			this.Name = "DI.WindowCreateDatabase";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowCreateDatabase");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DI.WindowCreateDatabase.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.WidthRequest = 300;
			this.entry1.HeightRequest = 40;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w1.X = 48;
			w1.Y = 23;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button();
			this.button4.WidthRequest = 200;
			this.button4.HeightRequest = 50;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Створити");
			this.fixed1.Add(this.button4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button4]));
			w2.X = 98;
			w2.Y = 90;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 173;
			this.Show();
			this.button4.Pressed += new global::System.EventHandler(this.OnButton4Pressed);
		}
	}
}
