
// This file has been generated by the GUI designer. Do not modify.
namespace DI
{
	public partial class WindowAddValue
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.Label label10;

		private global::Gtk.Entry entry3;

		private global::Gtk.Button button1;

		private global::Gtk.Entry entry1;

		private global::Gtk.Entry entry2;

		private global::Gtk.Entry entry5;

		private global::Gtk.Entry entry4;

		private global::Gtk.Entry entry7;

		private global::Gtk.Entry entry8;

		private global::Gtk.Entry entry6;

		private global::Gtk.Entry entry9;

		private global::Gtk.Entry entry10;

		private global::Gtk.Label label1;

		private global::Gtk.Label label2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DI.WindowAddValue
			this.Name = "DI.WindowAddValue";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowAddValue");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DI.WindowAddValue.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("label2");
			this.fixed1.Add(this.label3);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
			w1.X = 10;
			w1.Y = 152;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("label3");
			this.fixed1.Add(this.label4);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label4]));
			w2.X = 10;
			w2.Y = 198;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("label4");
			this.fixed1.Add(this.label5);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label5]));
			w3.X = 10;
			w3.Y = 244;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("label5");
			this.fixed1.Add(this.label6);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label6]));
			w4.X = 10;
			w4.Y = 290;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("label6");
			this.fixed1.Add(this.label7);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label7]));
			w5.X = 10;
			w5.Y = 336;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("label7");
			this.fixed1.Add(this.label8);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label8]));
			w6.X = 10;
			w6.Y = 382;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("label8");
			this.fixed1.Add(this.label9);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label9]));
			w7.X = 10;
			w7.Y = 428;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("label9");
			this.fixed1.Add(this.label10);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label10]));
			w8.X = 10;
			w8.Y = 474;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry3 = new global::Gtk.Entry();
			this.entry3.WidthRequest = 250;
			this.entry3.HeightRequest = 50;
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '•';
			this.fixed1.Add(this.entry3);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry3]));
			w9.X = 160;
			w9.Y = 136;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Додати");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w10.X = 347;
			w10.Y = 8;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.WidthRequest = 250;
			this.entry1.HeightRequest = 50;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed1.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry1]));
			w11.X = 160;
			w11.Y = 44;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.WidthRequest = 250;
			this.entry2.HeightRequest = 50;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed1.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry2]));
			w12.X = 160;
			w12.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry5 = new global::Gtk.Entry();
			this.entry5.WidthRequest = 250;
			this.entry5.HeightRequest = 50;
			this.entry5.CanFocus = true;
			this.entry5.Name = "entry5";
			this.entry5.IsEditable = true;
			this.entry5.InvisibleChar = '•';
			this.fixed1.Add(this.entry5);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry5]));
			w13.X = 160;
			w13.Y = 182;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry4 = new global::Gtk.Entry();
			this.entry4.WidthRequest = 250;
			this.entry4.HeightRequest = 50;
			this.entry4.CanFocus = true;
			this.entry4.Name = "entry4";
			this.entry4.IsEditable = true;
			this.entry4.InvisibleChar = '•';
			this.fixed1.Add(this.entry4);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry4]));
			w14.X = 160;
			w14.Y = 228;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.WidthRequest = 250;
			this.entry7.HeightRequest = 50;
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '•';
			this.fixed1.Add(this.entry7);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry7]));
			w15.X = 160;
			w15.Y = 320;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.WidthRequest = 250;
			this.entry8.HeightRequest = 50;
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '•';
			this.fixed1.Add(this.entry8);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry8]));
			w16.X = 160;
			w16.Y = 366;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry6 = new global::Gtk.Entry();
			this.entry6.WidthRequest = 250;
			this.entry6.HeightRequest = 50;
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.fixed1.Add(this.entry6);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry6]));
			w17.X = 160;
			w17.Y = 274;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry9 = new global::Gtk.Entry();
			this.entry9.WidthRequest = 250;
			this.entry9.HeightRequest = 50;
			this.entry9.CanFocus = true;
			this.entry9.Name = "entry9";
			this.entry9.IsEditable = true;
			this.entry9.InvisibleChar = '•';
			this.fixed1.Add(this.entry9);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry9]));
			w18.X = 160;
			w18.Y = 412;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.entry10 = new global::Gtk.Entry();
			this.entry10.WidthRequest = 250;
			this.entry10.HeightRequest = 50;
			this.entry10.CanFocus = true;
			this.entry10.Name = "entry10";
			this.entry10.IsEditable = true;
			this.entry10.InvisibleChar = '•';
			this.fixed1.Add(this.entry10);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.entry10]));
			w19.X = 160;
			w19.Y = 458;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed1.Add(this.label1);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
			w20.X = 10;
			w20.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("label1");
			this.fixed1.Add(this.label2);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
			w21.X = 10;
			w21.Y = 106;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 424;
			this.DefaultHeight = 533;
			this.Show();
			this.button1.Pressed += new global::System.EventHandler(this.OnButton1Pressed);
		}
	}
}
