
// This file has been generated by the GUI designer. Do not modify.
namespace DI
{
	public partial class WindowAddUser
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Entry entry1;

		private global::Gtk.Entry entry2;

		private global::Gtk.Label label2;

		private global::Gtk.Label label1;

		private global::Gtk.Button button3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget DI.WindowAddUser
			this.Name = "DI.WindowAddUser";
			this.Title = global::Mono.Unix.Catalog.GetString("WindowAddUser");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child DI.WindowAddUser.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.WidthRequest = 200;
			this.entry1.HeightRequest = 40;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed2.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry1]));
			w1.X = 100;
			w1.Y = 15;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.WidthRequest = 200;
			this.entry2.HeightRequest = 40;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed2.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry2]));
			w2.X = 100;
			w2.Y = 70;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Пароль");
			this.fixed2.Add(this.label2);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label2]));
			w3.X = 45;
			w3.Y = 80;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Имʼя");
			this.fixed2.Add(this.label1);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label1]));
			w4.X = 45;
			w4.Y = 30;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Додати");
			this.fixed2.Add(this.button3);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button3]));
			w5.X = 317;
			w5.Y = 134;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 406;
			this.DefaultHeight = 183;
			this.Show();
			this.button3.Pressed += new global::System.EventHandler(this.OnButton3Pressed);
		}
	}
}
